export const estates = [
  {
      "id": 1,
      "buildingCompanyName": "Baytik",
      "residentialComplexName": "Байтик недвижимость",
      "section": "A",
      "corner": true,
      "renovation": "Жаны нахуй",
      "district": "Центр города",
      "exactAddress": "Мкр. Джал",
      "numberOfRooms": 3,
      "totalArea": 75,
      "floor": 5,
      "documentation": "Доступна",
      "heating": "Центральное отопление",
      "description": "Просторная квартира с красивым видом",
      "furniture": "Полностью меблирована",
      "priceVisible": "300000",
      "priceHidden": "140000",
      "photos": [
          "https://img5.lalafo.com/i/posters/api/a0/41/69/5a1c3ed49a3740b8c383b79d0c.jpeg",
      ],
      "series": null,
      "user": "Amandos"
  },
  {
      "id": 2,
      "buildingCompanyName": "Ихлас",
      "residentialComplexName": "Байтик недвижимость",
      "section": "A",
      "corner": true,
      "renovation": "Элитка",
      "district": "Центр города",
      "exactAddress": "Мкр. Тунгуч",
      "numberOfRooms": 5,
      "totalArea": 95,
      "floor": 20,
      "documentation": "Доступна",
      "heating": "Центральное отопление",
      "description": "Просторная квартира с нихуевым видом",
      "furniture": "Полностью меблирована",
      "priceVisible": "500000",
      "priceHidden": "170000",
      "photos": [
          "https://elitka.kg/images/object/798/jk_discovery.jpg",
      ],
      "series": null,
      "user": "Meder"
  },
  {
      "id": 3,
      "buildingCompanyName": "Ихлас",
      "residentialComplexName": "Байтик недвижимость",
      "section": "A",
      "corner": true,
      "renovation": "Элитка",
      "district": "Центр города",
      "exactAddress": "Мкр. Тунгуч",
      "numberOfRooms": 5,
      "totalArea": 95,
      "floor": 20,
      "documentation": "Доступна",
      "heating": "Центральное отопление",
      "description": "Просторная квартира с нихуевым видом",
      "furniture": "Полностью меблирована",
      "priceVisible": "500000",
      "priceHidden": "170000",
      "photos": [
          "https://salexy.kg/images/img_kg/474x354/6f/fe/6ffeeff258e3556550f90bedbc2c985b.webp",
      ],
      "series": null,
      "user": "Meder"
  },
  {
      "id": 4,
      "buildingCompanyName": "Ихлас",
      "residentialComplexName": "Байтик недвижимость",
      "section": "A",
      "corner": true,
      "renovation": "Элитка",
      "district": "Центр города",
      "exactAddress": "Мкр. Тунгуч",
      "numberOfRooms": 5,
      "totalArea": 95,
      "floor": 20,
      "documentation": "Доступна",
      "heating": "Центральное отопление",
      "description": "Просторная квартира с нихуевым видом",
      "furniture": "Полностью меблирована",
      "priceVisible": "500000",
      "priceHidden": "170000",
      "photos": [
          "https://img5.lalafo.com/i/posters/api/a0/41/69/5a1c3ed49a3740b8c383b79d0c.jpeg",
      ],
      "series": null,
      "user": "Meder"
  },
  {
      "id": 4,
      "buildingCompanyName": "Ихлас",
      "residentialComplexName": "Байтик недвижимость",
      "section": "A",
      "corner": true,
      "renovation": "Элитка",
      "district": "Центр города",
      "exactAddress": "Мкр. Тунгуч",
      "numberOfRooms": 5,
      "totalArea": 95,
      "floor": 20,
      "documentation": "Доступна",
      "heating": "Центральное отопление",
      "description": "Просторная квартира с нихуевым видом",
      "furniture": "Полностью меблирована",
      "priceVisible": "500000",
      "priceHidden": "170000",
      "photos": [
          "https://img5.lalafo.com/i/posters/api/a0/41/69/5a1c3ed49a3740b8c383b79d0c.jpeg",
      ],
      "series": null,
      "user": "Meder"
  },
  {
      "id": 4,
      "buildingCompanyName": "Ихлас",
      "residentialComplexName": "Байтик недвижимость",
      "section": "A",
      "corner": true,
      "renovation": "Элитка",
      "district": "Центр города",
      "exactAddress": "Мкр. Тунгуч",
      "numberOfRooms": 5,
      "totalArea": 95,
      "floor": 20,
      "documentation": "Доступна",
      "heating": "Центральное отопление",
      "description": "Просторная квартира с нихуевым видом",
      "furniture": "Полностью меблирована",
      "priceVisible": "500000",
      "priceHidden": "170000",
      "photos": [
          "https://img5.lalafo.com/i/posters/api/a0/41/69/5a1c3ed49a3740b8c383b79d0c.jpeg",
      ],
      "series": null,
      "user": "Meder"
  },
  {
      "id": 4,
      "buildingCompanyName": "Ихлас",
      "residentialComplexName": "Байтик недвижимость",
      "section": "A",
      "corner": true,
      "renovation": "Элитка",
      "district": "Центр города",
      "exactAddress": "Мкр. Тунгуч",
      "numberOfRooms": 5,
      "totalArea": 95,
      "floor": 20,
      "documentation": "Доступна",
      "heating": "Центральное отопление",
      "description": "Просторная квартира с нихуевым видом",
      "furniture": "Полностью меблирована",
      "priceVisible": "500000",
      "priceHidden": "170000",
      "photos": [
          "https://img5.lalafo.com/i/posters/api/a0/41/69/5a1c3ed49a3740b8c383b79d0c.jpeg",
      ],
      "series": null,
      "user": "Meder"
  },
  {
      "id": 4,
      "buildingCompanyName": "Ихлас",
      "residentialComplexName": "Байтик недвижимость",
      "section": "A",
      "corner": true,
      "renovation": "Элитка",
      "district": "Центр города",
      "exactAddress": "Мкр. Тунгуч",
      "numberOfRooms": 5,
      "totalArea": 95,
      "floor": 20,
      "documentation": "Доступна",
      "heating": "Центральное отопление",
      "description": "Просторная квартира с нихуевым видом",
      "furniture": "Полностью меблирована",
      "priceVisible": "500000",
      "priceHidden": "170000",
      "photos": [
          "https://img5.lalafo.com/i/posters/api/a0/41/69/5a1c3ed49a3740b8c383b79d0c.jpeg",
      ],
      "series": null,
      "user": "Meder"
  },
  {
      "id": 4,
      "buildingCompanyName": "Ихлас",
      "residentialComplexName": "Байтик недвижимость",
      "section": "A",
      "corner": true,
      "renovation": "Элитка",
      "district": "Центр города",
      "exactAddress": "Мкр. Тунгуч",
      "numberOfRooms": 5,
      "totalArea": 95,
      "floor": 20,
      "documentation": "Доступна",
      "heating": "Центральное отопление",
      "description": "Просторная квартира с нихуевым видом",
      "furniture": "Полностью меблирована",
      "priceVisible": "500000",
      "priceHidden": "170000",
      "photos": [
          "https://img5.lalafo.com/i/posters/api/a0/41/69/5a1c3ed49a3740b8c383b79d0c.jpeg",
      ],
      "series": null,
      "user": "Meder"
  },
  {
      "id": 4,
      "buildingCompanyName": "Ихлас",
      "residentialComplexName": "Байтик недвижимость",
      "section": "A",
      "corner": true,
      "renovation": "Элитка",
      "district": "Центр города",
      "exactAddress": "Мкр. Тунгуч",
      "numberOfRooms": 5,
      "totalArea": 95,
      "floor": 20,
      "documentation": "Доступна",
      "heating": "Центральное отопление",
      "description": "Просторная квартира с нихуевым видом",
      "furniture": "Полностью меблирована",
      "priceVisible": "500000",
      "priceHidden": "170000",
      "photos": [
          "https://img5.lalafo.com/i/posters/api/a0/41/69/5a1c3ed49a3740b8c383b79d0c.jpeg",
      ],
      "series": null,
      "user": "Meder"
  },
  {
      "id": 4,
      "buildingCompanyName": "Ихлас",
      "residentialComplexName": "Байтик недвижимость",
      "section": "A",
      "corner": true,
      "renovation": "Элитка",
      "district": "Центр города",
      "exactAddress": "Мкр. Тунгуч",
      "numberOfRooms": 5,
      "totalArea": 95,
      "floor": 20,
      "documentation": "Доступна",
      "heating": "Центральное отопление",
      "description": "Просторная квартира с нихуевым видом",
      "furniture": "Полностью меблирована",
      "priceVisible": "500000",
      "priceHidden": "170000",
      "photos": [
          "https://img5.lalafo.com/i/posters/api/a0/41/69/5a1c3ed49a3740b8c383b79d0c.jpeg",
      ],
      "series": null,
      "user": "Meder"
  },
  {
      "id": 4,
      "buildingCompanyName": "Ихлас",
      "residentialComplexName": "Байтик недвижимость",
      "section": "A",
      "corner": true,
      "renovation": "Элитка",
      "district": "Центр города",
      "exactAddress": "Мкр. Тунгуч",
      "numberOfRooms": 5,
      "totalArea": 95,
      "floor": 20,
      "documentation": "Доступна",
      "heating": "Центральное отопление",
      "description": "Просторная квартира с нихуевым видом",
      "furniture": "Полностью меблирована",
      "priceVisible": "500000",
      "priceHidden": "170000",
      "photos": [
          "https://img5.lalafo.com/i/posters/api/a0/41/69/5a1c3ed49a3740b8c383b79d0c.jpeg",
      ],
      "series": null,
      "user": "Meder"
  },
  {
      "id": 4,
      "buildingCompanyName": "Ихлас",
      "residentialComplexName": "Байтик недвижимость",
      "section": "A",
      "corner": true,
      "renovation": "Элитка",
      "district": "Центр города",
      "exactAddress": "Мкр. Тунгуч",
      "numberOfRooms": 5,
      "totalArea": 95,
      "floor": 20,
      "documentation": "Доступна",
      "heating": "Центральное отопление",
      "description": "Просторная квартира с нихуевым видом",
      "furniture": "Полностью меблирована",
      "priceVisible": "500000",
      "priceHidden": "170000",
      "photos": [
          "https://img5.lalafo.com/i/posters/api/a0/41/69/5a1c3ed49a3740b8c383b79d0c.jpeg",
      ],
      "series": null,
      "user": "Meder"
  },
  {
      "id": 4,
      "buildingCompanyName": "Ихлас",
      "residentialComplexName": "Байтик недвижимость",
      "section": "A",
      "corner": true,
      "renovation": "Элитка",
      "district": "Центр города",
      "exactAddress": "Мкр. Тунгуч",
      "numberOfRooms": 5,
      "totalArea": 95,
      "floor": 20,
      "documentation": "Доступна",
      "heating": "Центральное отопление",
      "description": "Просторная квартира с нихуевым видом",
      "furniture": "Полностью меблирована",
      "priceVisible": "500000",
      "priceHidden": "170000",
      "photos": [
          "https://img5.lalafo.com/i/posters/api/a0/41/69/5a1c3ed49a3740b8c383b79d0c.jpeg",
      ],
      "series": null,
      "user": "Meder"
  },
  {
      "id": 4,
      "buildingCompanyName": "Ихлас",
      "residentialComplexName": "Байтик недвижимость",
      "section": "A",
      "corner": true,
      "renovation": "Элитка",
      "district": "Центр города",
      "exactAddress": "Мкр. Тунгуч",
      "numberOfRooms": 5,
      "totalArea": 95,
      "floor": 20,
      "documentation": "Доступна",
      "heating": "Центральное отопление",
      "description": "Просторная квартира с нихуевым видом",
      "furniture": "Полностью меблирована",
      "priceVisible": "500000",
      "priceHidden": "170000",
      "photos": [
          "https://img5.lalafo.com/i/posters/api/a0/41/69/5a1c3ed49a3740b8c383b79d0c.jpeg",
      ],
      "series": null,
      "user": "Meder"
  },
  {
      "id": 4,
      "buildingCompanyName": "Ихлас",
      "residentialComplexName": "Байтик недвижимость",
      "section": "A",
      "corner": true,
      "renovation": "Элитка",
      "district": "Центр города",
      "exactAddress": "Мкр. Тунгуч",
      "numberOfRooms": 5,
      "totalArea": 95,
      "floor": 20,
      "documentation": "Доступна",
      "heating": "Центральное отопление",
      "description": "Просторная квартира с нихуевым видом",
      "furniture": "Полностью меблирована",
      "priceVisible": "500000",
      "priceHidden": "170000",
      "photos": [
          "https://img5.lalafo.com/i/posters/api/a0/41/69/5a1c3ed49a3740b8c383b79d0c.jpeg",
      ],
      "series": null,
      "user": "Meder"
  },
]



